### ISSUE TITLE
DATA入力例 or  原本シートを作成する

### ISSUE THREAD

**Issue by SAMMY7th** [rimria/stepn_fee_spreadsheet#3]
## 目的
- 現在開発用ではDATAシートのみ、配布用では「DATA原本」「DATA」シートをわけている。ここの仕様を明確にし、開発用と配布用の仕様を統一する。

## やること
- 必要なのは原本なのか入力例なのか、シートの役割を明確にする
- 開発・更新手順が煩雑にならないフローを考える
- 仕様を決めたらシートに反映する

## 完了条件
- ユーザーがDATAシートをスムーズに入力開始できるようになる
- DATAシートの開発・更新手順が極力シンプルなフローとなっている

## 参考資料(あれば)

**Comment by SAMMY7th** [comment]
各操作１回ずつぐらいあるシートを入力例として用意する。

**Comment by diagram-wolf** [comment]
2022/03/10…DATA（記入例）シート作成済み
